import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | MatchMyStudy",
  description:
    "Read the Terms & Conditions for using MatchMyStudy, including accounts, consultant profiles, reviews, subscriptions, third-party services, advertising, and affiliate links.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white text-slate-900">
      <div className="mx-auto max-w-4xl px-6 py-16">
        <h1 className="text-4xl font-bold tracking-tight">
          Terms & Conditions
        </h1>

        <p className="mt-3 text-sm text-slate-500">
          Last updated: 29 September 2026
        </p>

        <div className="mt-10 space-y-10 leading-7 text-slate-700">
          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              1. Introduction
            </h2>

            <p className="mt-4">
              Welcome to MatchMyStudy. MatchMyStudy is a platform designed to
              help students explore study-abroad opportunities, countries,
              universities, study programmes, education consultants, and
              online learning resources.
            </p>

            <p className="mt-4">
              These Terms & Conditions govern your access to and use of the
              MatchMyStudy website and services. By accessing or using
              MatchMyStudy, you agree to these Terms & Conditions.
            </p>

            <p className="mt-4">
              If you do not agree with these terms, please do not use
              MatchMyStudy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              2. About MatchMyStudy
            </h2>

            <p className="mt-4">
              MatchMyStudy provides information and tools intended to help
              users explore international education opportunities.
            </p>

            <p className="mt-4">
              The platform may provide information about countries,
              universities, study programmes, education consultants, online
              courses, and other education-related resources.
            </p>

            <p className="mt-4">
              MatchMyStudy does not guarantee admission to any university or
              educational institution and does not guarantee visa approval,
              employment, immigration outcomes, scholarships, or other
              educational or career outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              3. Educational Information
            </h2>

            <p className="mt-4">
              Information displayed on MatchMyStudy may include programme
              names, tuition information, programme descriptions, durations,
              study locations, entry information, and other educational
              details.
            </p>

            <p className="mt-4">
              Programme availability, tuition fees, admission requirements,
              application deadlines, scholarships, visa requirements, and
              other information may change over time.
            </p>

            <p className="mt-4">
              Users should verify important information directly with the
              relevant university, educational institution, government
              authority, or other official source before making decisions or
              submitting applications.
            </p>

            <p className="mt-4">
              MatchMyStudy does not guarantee that all information displayed
              on the website is complete, current, or error-free.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              4. Study Matching and Recommendations
            </h2>

            <p className="mt-4">
              MatchMyStudy may provide tools that help users compare or match
              study destinations, universities, programmes, or other
              education-related options based on information entered by the
              user.
            </p>

            <p className="mt-4">
              Any match percentage, recommendation, comparison, ranking, or
              result generated by the platform is intended as informational
              guidance only.
            </p>

            <p className="mt-4">
              Such results should not be interpreted as a guarantee that a
              particular country, university, programme, or consultant is
              suitable for a user.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              5. User Accounts
            </h2>

            <p className="mt-4">
              Some MatchMyStudy features may require you to create an
              account.
            </p>

            <p className="mt-4">
              You are responsible for providing accurate information and for
              keeping your account credentials secure.
            </p>

            <p className="mt-4">
              You must not use another person's account without permission or
              provide false information for the purpose of misleading other
              users or MatchMyStudy.
            </p>

            <p className="mt-4">
              MatchMyStudy may restrict or suspend accounts where necessary
              to protect the platform, its users, or the integrity of the
              service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              6. Consultant Profiles
            </h2>

            <p className="mt-4">
              MatchMyStudy may allow education consultants or consultancy
              businesses to create or claim profiles on the platform.
            </p>

            <p className="mt-4">
              Consultants are responsible for ensuring that information they
              provide about themselves, their services, contact details,
              locations, experience, and other profile information is
              accurate and not misleading.
            </p>

            <p className="mt-4">
              MatchMyStudy may review, verify, modify, restrict, or remove
              consultant profile information where reasonably necessary.
            </p>

            <p className="mt-4">
              The presence of a consultant profile on MatchMyStudy does not
              by itself constitute an endorsement, recommendation, guarantee,
              or certification of that consultant.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              7. Reviews and User-Generated Content
            </h2>

            <p className="mt-4">
              Users may be able to submit reviews, ratings, comments, or
              other content to MatchMyStudy.
            </p>

            <p className="mt-4">
              Users are responsible for the content they submit and must not
              submit content that is unlawful, fraudulent, defamatory,
              threatening, abusive, misleading, or otherwise inappropriate.
            </p>

            <p className="mt-4">
              Users must not submit another person's private or sensitive
              information without an appropriate legal basis or permission.
            </p>

            <p className="mt-4">
              MatchMyStudy may remove content that violates these Terms &
              Conditions or applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              8. Pro Subscription
            </h2>

            <p className="mt-4">
              MatchMyStudy may offer paid Pro features to eligible
              consultants or other users.
            </p>

            <p className="mt-4">
              The price, billing period, features, and other applicable
              subscription details will be displayed before a subscription is
              purchased.
            </p>

            <p className="mt-4">
              Subscription payments may be processed through third-party
              payment providers such as Stripe.
            </p>

            <p className="mt-4">
              A subscription may automatically renew according to the terms
              displayed at the time of purchase unless cancelled before the
              applicable renewal date.
            </p>

            <p className="mt-4">
              If a subscription is cancelled, access to paid features may
              continue until the end of the applicable paid subscription
              period, unless otherwise stated.
            </p>

            <p className="mt-4">
              Refunds, cancellations, and payment-related matters are subject
              to the applicable purchase terms and payment provider
              requirements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              9. Third-Party Websites and Services
            </h2>

            <p className="mt-4">
              MatchMyStudy may contain links to websites, platforms, services,
              universities, educational institutions, consultants, or other
              third parties.
            </p>

            <p className="mt-4">
              Third-party websites and services operate independently from
              MatchMyStudy and may have their own terms, privacy policies, and
              other conditions.
            </p>

            <p className="mt-4">
              MatchMyStudy is not responsible for the content, availability,
              security, policies, products, services, or practices of
              third-party websites.
            </p>

            <p className="mt-4">
              Users should review the terms and privacy policies of
              third-party websites before using their services or providing
              personal information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              10. Affiliate Links and Commercial Relationships
            </h2>

            <p className="mt-4">
              MatchMyStudy may participate in affiliate marketing programmes
              or other commercial partnerships.
            </p>

            <p className="mt-4">
              Some links on MatchMyStudy may be affiliate links. If you use
              an affiliate link and subsequently make a qualifying purchase
              or take another qualifying action, MatchMyStudy may receive a
              commission or other compensation at no additional cost to you,
              where applicable.
            </p>

            <p className="mt-4">
              Affiliate relationships do not necessarily mean that a
              particular product, service, university, course, or provider is
              endorsed or guaranteed by MatchMyStudy.
            </p>

            <p className="mt-4">
              Any affiliate relationship will be disclosed where required by
              applicable law or platform requirements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              11. Advertising
            </h2>

            <p className="mt-4">
              MatchMyStudy may display advertisements provided by
              third-party advertising platforms, including Google AdSense or
              other advertising providers.
            </p>

            <p className="mt-4">
              Advertisements may be selected or delivered based on factors
              determined by the applicable advertising provider and, where
              permitted and consented to, information about users or their
              interactions with the website.
            </p>

            <p className="mt-4">
              MatchMyStudy does not necessarily endorse products or services
              shown in advertisements.
            </p>

            <p className="mt-4">
              Advertising and cookie practices are also described in the
              MatchMyStudy Privacy Policy and applicable cookie or consent
              information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              12. Intellectual Property
            </h2>

            <p className="mt-4">
              Unless otherwise stated, the MatchMyStudy website, including its
              branding, logo, design, original text, software, graphics, and
              other original materials, is owned by or licensed to
              MatchMyStudy.
            </p>

            <p className="mt-4">
              You may use the website for personal and lawful purposes. You
              must not copy, reproduce, modify, distribute, sell, or exploit
              MatchMyStudy content without appropriate permission, except
              where permitted by applicable law.
            </p>

            <p className="mt-4">
              Third-party names, logos, trademarks, university names, and
              other intellectual property remain the property of their
              respective owners.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              13. Prohibited Use
            </h2>

            <p className="mt-4">
              You must not use MatchMyStudy to:
            </p>

            <ul className="mt-4 list-disc space-y-2 pl-6">
              <li>Break applicable laws or regulations.</li>
              <li>
                Attempt to gain unauthorised access to accounts, systems, or
                data.
              </li>
              <li>
                Introduce malicious software, harmful code, or other
                disruptive material.
              </li>
              <li>
                Submit fraudulent, misleading, or deliberately inaccurate
                information.
              </li>
              <li>
                Harass, threaten, abuse, or impersonate other users.
              </li>
              <li>
                Scrape, copy, or systematically collect website content in a
                way that violates applicable law or these terms.
              </li>
              <li>
                Interfere with the normal operation or security of the
                website.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              14. Availability of the Service
            </h2>

            <p className="mt-4">
              MatchMyStudy aims to keep the platform available and
              functional, but uninterrupted availability cannot be
              guaranteed.
            </p>

            <p className="mt-4">
              The service may occasionally be unavailable because of
              maintenance, updates, technical problems, security issues,
              third-party service interruptions, or circumstances outside
              MatchMyStudy's reasonable control.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              15. Limitation of Liability
            </h2>

            <p className="mt-4">
              MatchMyStudy provides the platform and its information on an
              informational basis.
            </p>

            <p className="mt-4">
              To the extent permitted by applicable law, MatchMyStudy is not
              responsible for losses or damages resulting from reliance on
              information displayed on the platform, decisions made based on
              that information, third-party services, university admission
              decisions, visa decisions, employment outcomes, or other
              outcomes that are outside MatchMyStudy's control.
            </p>

            <p className="mt-4">
              Nothing in these Terms & Conditions excludes or limits liability
              where such exclusion or limitation is not permitted under
              applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              16. Privacy
            </h2>

            <p className="mt-4">
              Your use of MatchMyStudy is also subject to our Privacy Policy,
              which explains how personal data may be collected, used, stored,
              and protected.
            </p>

            <p className="mt-4">
              You can read the Privacy Policy on the MatchMyStudy website.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              17. Changes to These Terms
            </h2>

            <p className="mt-4">
              MatchMyStudy may update these Terms & Conditions from time to
              time to reflect changes to the platform, services, legal
              requirements, or business practices.
            </p>

            <p className="mt-4">
              The latest version will be published on this page with an
              updated date.
            </p>

            <p className="mt-4">
              Continued use of MatchMyStudy after an updated version becomes
              effective constitutes acceptance of the updated terms, to the
              extent permitted by applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              18. Contact
            </h2>

            <p className="mt-4">
              If you have questions about these Terms & Conditions, please
              contact:
            </p>

            <div className="mt-4 rounded-2xl bg-slate-50 p-6">
              <p className="font-semibold text-slate-900">MatchMyStudy</p>
              <p className="mt-2">Hämeenlinna, Finland</p>
              <p className="mt-2">
                Email:{" "}
                <a
                  href="mailto:dravindu120@gmail.com"
                  className="text-blue-600 hover:underline"
                >
                  dravindu120@gmail.com
                </a>
              </p>
            </div>
          </section>
        </div>
      </div>
    </main>
  );
}